db:
  mysql:
    host: prod.localhost.com
    port: 3306
    user: root
    password: password
    db: mydatabase
    max_lifetime: 3 # minutes
    max_open_conns: 10
    max_idle_conns: 5
    query: "charset=utf8"